# Generated by Django 5.2.7 on 2025-10-24 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(choices=[('CLARK_MAIN', 'Clark Main Gate'), ('SM_CLARK', 'SM City Clark'), ('CLARK_PARADE', 'Clark Parade Grounds'), ('WIDUS_HOTEL', 'Widus Hotel & Casino'), ('MARQUEE_MALL', 'Marquee Mall'), ('CLARK_MUSEUM', 'Clark Museum'), ('AQUA_PLANET', 'Aqua Planet'), ('CLARK_AIRPORT', 'Clark International Airport'), ('CDC', 'Clark Development Corporation'), ('FONTANA', 'Fontana Leisure Park'), ('CLARK_SUN', 'Clark Sun Valley'), ('MIDORI_HOTEL', 'Midori Clark Hotel'), ('ROYCE_HOTEL', 'Royce Hotel & Casino')], help_text='Select pickup location', max_length=255)),
                ('destination', models.CharField(choices=[('CLARK_MAIN', 'Clark Main Gate'), ('SM_CLARK', 'SM City Clark'), ('CLARK_PARADE', 'Clark Parade Grounds'), ('WIDUS_HOTEL', 'Widus Hotel & Casino'), ('MARQUEE_MALL', 'Marquee Mall'), ('CLARK_MUSEUM', 'Clark Museum'), ('AQUA_PLANET', 'Aqua Planet'), ('CLARK_AIRPORT', 'Clark International Airport'), ('CDC', 'Clark Development Corporation'), ('FONTANA', 'Fontana Leisure Park'), ('CLARK_SUN', 'Clark Sun Valley'), ('MIDORI_HOTEL', 'Midori Clark Hotel'), ('ROYCE_HOTEL', 'Royce Hotel & Casino')], help_text='Select destination location', max_length=255)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PHP', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_customer', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(limit_choices_to={'user_role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(1, 'Ride Requested'), (2, 'Rider Accepted'), (3, 'Rider Arrived at Pickup'), (4, 'Journey Started'), (5, 'Journey Completed'), (6, 'Ride Cancelled')], help_text='Current step in the ride process')),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rides.ride')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
